# Generated by Django 4.0.6 on 2022-09-12 12:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sets', 'sets'), ('lunch', 'lunch'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('salad', 'salad'), ('drink', 'drink')], max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_api.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='media/food.svg', upload_to='uploaded_media')),
                ('title', models.CharField(max_length=35)),
                ('calories', models.FloatField(default=0.0)),
                ('carbohydrates', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('ingredients', models.CharField(max_length=255)),
                ('kcal', models.FloatField(default=0.0)),
                ('category', models.ManyToManyField(related_name='categories', to='menu_api.category')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ManyToManyField(related_name='foods', to='menu_api.fit'),
        ),
    ]
