# Generated by Django 4.1 on 2022-08-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default="media/avatar.jpeg", upload_to="uploaded_media"
            ),
        ),
    ]
